{{ if .Values.constraints.k8sMountVolume }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sMountVolumeHostPath
metadata:
  name: k8s-mount-volume-hostpath
  labels:
    argocd.argoproj.io/instance: gatekeeper
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    operations:
      - "CREATE"
      - "UPDATE"
    exemptImages:
      - docker.elastic.co/beats/filebeat
      - docker.elastic.co/beats/journalbeat
      - docker.elastic.co/beats/metricbeat
      - hashicorp/vault
      - k8s.gcr.io/etcd
      - k8s.gcr.io/kube-apiserver
      - k8s.gcr.io/kube-controller-manager
      - k8s.gcr.io/kube-proxy
      - k8s.gcr.io/kube-scheduler
      - longhornio/csi-attacher
      - longhornio/csi-node-driver-registrar
      - longhornio/csi-provisioner
      - longhornio/csi-resizer
      - longhornio/csi-snapshotter
      - longhornio/livenessprobe
      - longhornio/longhorn-engine
      - longhornio/longhorn-instance-manager
      - longhornio/longhorn-manager
      - quay.io/coreos/flannel
      - quay.io/prometheus/node-exporter
      - registry.ftech.ai/ftech-fingerprint/fingersprint-api
      - registry.ftech.ai/is-chart/etcd-backup
      - registry.ftech.ai/is-chart/pvc-exporter
      - registry.ftech.ai/platform/fingerprint-notify
      - registry.ftech.ai/platform/fingersprint-api
      - registry.ftech.ai/platform/hcns-cms
      - registry.k8s.io/sig-storage/csi-node-driver-registrar
      - registry.k8s.io/sig-storage/csi-provisioner
      - registry.k8s.io/sig-storage/livenessprobe
      - registry.k8s.io/sig-storage/nfsplugin
{{ end }}
