annotations:
  artifacthub.io/changes: |
    - "Allow defining imagePullSecrets"
apiVersion: v1
appVersion: v1.6.3
description: Kubernetes Native Policy Management
home: https://kyverno.io/
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
keywords:
- kubernetes
- nirmata
- policy agent
- validating webhook
- admissions controller
kubeVersion: '>=1.16.0-0'
maintainers:
- name: Nirmata
  url: https://kyverno.io/
name: kyverno
sources:
- https://github.com/kyverno/kyverno
version: v2.3.4
