apiVersion: v1
kind: Service
metadata:
  name: devsecops-dev
spec: 
  type: NodePort
  ports:
    - name: https
      port: 943
      protocol: TCP
      targetPort: 943
    - name: https2
      port: 9443
      protocol: TCP
      targetPort: 9443
      nodePort: 31223
    - name: udp
      port: 1194
      protocol: UDP
      targetPort: 9443
  selector:
    app.kubernetes.io/instance: openvpn
    app.kubernetes.io/name: openvpn