apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-template-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: intern
    server: https://kubernetes.default.svc
  project: intern
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/intern/monitoring.git
    targetRevision: local
    path: helm-template/helm
    helm:
      releaseName: helm-template
      version: v3
      valueFiles:
      - values-local.yaml
  syncPolicy:
    # automated:
    #   selfHeal: true
    #   prune: true
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
