helm:
  parameters:
  - name: poly.apps.kong-domain-sd.image.repository
    value: registry.ftech.ai/is-chart/kong-domain-sd
    forcestring: true
  - name: poly.apps.kong-domain-sd.image.tag
    value: f365-2022-10-26_03-03-09-21af644e
    forcestring: true
