apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds
  namespace: argocd
spec:
  secretStoreRef: # secret store
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-repo-creds # kubernetes secret name
    template: # output secret template
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  data:
  - secretKey: type
    remoteRef:
      key: secret/data/projects/argocd/manifest/master
      property: type
  - secretKey: url
    remoteRef:
      key: secret/data/projects/argocd/manifest/master
      property: url
  - secretKey: username
    remoteRef:
      key: secret/data/projects/argocd/manifest/master
      property: username
  - secretKey: password
    remoteRef:
      key: secret/data/projects/argocd/manifest/master
      property: password
