apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: argocd
spec:
  provider:
    vault:
      server: "https://vault-raft.prod.ftech.ai/"
      auth:
        kubernetes:
          mountPath: "kubernetes-local"
          role: "argocd-manifest-ro"