apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intern-vault-local
  namespace: argocd
  labels:
    owner: local
    env: local
    pic: namtt
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: intern
    server: https://kubernetes.default.svc
  project: intern
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/intern/monitoring.git
    targetRevision: local
    path: vault/helm
    helm:
      releaseName: vault
      version: v3
      valueFiles:
      - values-local.yaml
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
