pritunl-vpn:
  image:
    repository: jippi/pritunl
    tag: 1.30.3413.7
    pullPolicy: IfNotPresent
  service: 
    type: NodePort
    port: 30194
    nodePort: 30194
  mongodb:
    enabled: false
    auth:
      enabled: false
  ingress:
    enabled: true
    pathType: Prefix 
    hostname: vpn.ai.ftech.ai
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "https"
      nginx.ingress.kubernetes.io/whitelist-source-range: 14.232.166.121/32,113.20.108.35/32,118.70.125.152/32,113.160.224.57/32,118.69.70.245/32,118.69.61.27/32,115.73.208.235/32,192.168.20.0/24
      # nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    tls: true
    selfSigned: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - "ai-gpu-1"