dependency-track:
  frontend:
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi     
  apiserver:
    resources:
      requests:
        cpu: 0.2
      limits:
        cpu: 1.5
        memory: 10Gi
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      ## allow large bom.xml uploads:
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    host: dependency-track.dev.ftech.ai
    # ingressClassName: nginx
  