---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namtt
  annotations:
    kubernetes.io/service-account.name: "namtt"

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: namtt-sa-token
  annotations:
    kubernetes.io/service-account.name: "namtt"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namtt-admin-role
  annotations:
    kubernetes.io/service-account.name: "namtt"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namtt-admin-crb
  annotations:
    kubernetes.io/service-account.name: "namtt"
subjects:
- kind: ServiceAccount
  name: namtt 
  namespace: "users"
roleRef:
  kind: ClusterRole
  name: namtt-admin-role
  apiGroup: rbac.authorization.k8s.io
