apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dso-volume
  labels:
    app.kubernetes.io/name: openvpn
    app.kubernetes.io/instance: openvpn
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
