apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-regcred-test
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: argocd-local
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
    targetRevision: HEAD
    path: argocd-local/argocd-apps/regcred/nginx-regcred-manifest
    helm:
      releaseName: regcred
      version: v3
      valueFiles:
      - values-local.yaml
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - CreateNamespace=true
