apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    owner: IS
    pic: IS.namtt
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: metallb
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
    targetRevision: master
    path: argocd-local/argocd-apps/metallb
    directory:
      recurse: true
