apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus-db-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: milvus-db
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
    targetRevision: HEAD
    path: argocd-local/argocd-apps/milvus-db
    directory:
      recurse: true
