apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: nginx
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
    targetRevision: HEAD
    path: argocd-local/argocd-apps/nginx
    directory:
      recurse: true
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  # allowEmpty: true
    #  prune: true