apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: regcred
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd-local
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
    targetRevision: HEAD
    path: argocd-local/argocd-apps/regcred/app-of-apps
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true  
    syncOptions:
    - CreateNamespace=true
