apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terminal
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: terminal
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
    targetRevision: master
    path: argocd-local/argocd-apps/terminal
    directory:
      recurse: true