apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-resources-config
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: local
        namespace: nginx
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}-application-resources-config'
    spec:
      project: nginx
      source:
        repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
        targetRevision: master
        path: 'argocd-local/manifest/nginx/application-resources-config/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          allowEmpty: true
          prune: true
        syncOptions:
        - CreateNamespace=true
        
