{{ if .Values.K8sHostNetwork.enabled }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHostNetwork
metadata:
  name: k8s-host-network
  labels:
    {{- include "gatekeeper-constraints.labels" . | nindent 4 }}
spec:
  match:
    kinds: {{ toYaml .Values.K8sHostNetwork.matchKinds | nindent 6 }}
  parameters:
    operations:
      - "CREATE"
      - "UPDATE"
    exemptImages: {{ toYaml .Values.K8sHostNetwork.exemptImages | nindent 6 }}
{{ end }}