{{ if .Values.K8sHostNamespace.enabled }}
---
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8shostnamespace
  labels:
    {{- include "gatekeeper-constraints.labels" . | nindent 4 }}
  annotations:
    metadata.gatekeeper.sh/title: "Host Namespace"
    metadata.gatekeeper.sh/version: 1.0.0
    description: >-
      Disallows sharing of host PID and IPC namespaces by pod containers.
      Corresponds to the `hostPID` and `hostIPC` fields in a PodSecurityPolicy.
      For more information, see
      https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces
spec:
  crd:
    spec:
      names:
        kind: K8sHostNamespace
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            operations:
              type: array
              items:
                type: string
            exemptImages:
              description: >-
                Any container that uses an image that matches an entry in this list will be excluded
                from enforcement.
              type: array
              items:
                type: string

  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8shostnamespace

      import data.lib.k8shostnamespace.is_exempt
      import future.keywords.in
      
      input_pod := input.review.object

      input_containers[c] {
        c := input_pod.spec.containers[_]
      }
      input_containers[c] {
        c := input_pod.spec.initContainers[_]
      }
      input_containers[c] {
        c := input_pod.spec.ephemeralContainers[_]
      }

      input_share_hostnamespace(p) {
        p.spec.hostPID
      }

      input_share_hostnamespace(p) {
        p.spec.hostIPC
      }

      violation[{"msg": msg, "details": {}}] {
        input.review.operation in input.parameters.operations
        c := input_containers[_]
        not is_exempt(c)
        input_share_hostnamespace(input_pod)
        msg := sprintf("Sharing the host namespace is not allowed", [])
      }

    libs: 
    - |
      package lib.k8shostnamespace

      import future.keywords.in

      is_exempt(container) {
        exempt_images := object.get(object.get(input, "parameters", {}), "exemptImages", [])
        count(exempt_images) > 0
        img := split(container.image, ":")[0]
        img in exempt_images
      }
{{ end }}
