{{ if .Values.K8sHostNamespace.enabled }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHostNamespace
metadata:
  name: k8s-host-namespace
  labels:
    {{- include "gatekeeper-constraints.labels" . | nindent 4 }}
spec:
  match:
    kinds: {{ toYaml .Values.K8sHostNamespace.matchKinds | nindent 6 }}
  parameters:
    operations:
      - "CREATE"
      - "UPDATE"
    exemptImages: {{ toYaml .Values.K8sHostNamespace.exemptImages | nindent 6 }}
{{ end }}
