{{ if .Values.K8sPrivilegedContainer.enabled }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPrivilegedContainer
metadata:
  name: k8s-privileged-container
  labels:
    {{- include "gatekeeper-constraints.labels" . | nindent 4 }}
spec:
  match:
    kinds: {{ toYaml .Values.K8sPrivilegedContainer.matchKinds | nindent 6 }}
  parameters:
    operations:
      - "CREATE"
      - "UPDATE"
    exemptImages: {{ toYaml .Values.K8sPrivilegedContainer.exemptImages | nindent 6 }}
{{ end }}
