{{- if .Values.externalSecrets.create -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: external-secrets.io/v1beta1
{{- else -}}
apiVersion: external-secrets.io/v1alpha1
{{- end }}
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: {{ include "app.fullname" . }}
    kind: SecretStore
  target:
    {{- $regcred := (first .Values.imagePullSecrets).name }}    
    name: {{ $regcred }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
  data:
  - secretKey: .dockerconfigjson # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.dockerconfigjson.path }}
      property: dockerconfigjson    # vault key
{{- end }}
      