apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: terminal=registry.ftech.ai/public/terminal
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/manifest
    argocd-image-updater.argoproj.io/terminal.update-strategy: name
    argocd-image-updater.argoproj.io/terminal.allow-tags: regexp:^dev-[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9a-zA-Z]+$
    argocd-image-updater.argoproj.io/terminal.helm.image-name: poly.apps.terminal.image.repository
    argocd-image-updater.argoproj.io/terminal.helm.image-tag: poly.apps.terminal.image.tag
  name: terminal-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: terminal
    server: https://kubernetes.default.svc
  project: terminal
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
    targetRevision: master 
    path: argocd-local/manifest/terminal/helm
    helm:
      releaseName: terminal
      version: v3
      valueFiles:
      - values-local.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true  
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - FailOnSharedResource=true