openspeedtest:
  enabled: true
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
      nginx.ingress.kubernetes.io/whitelist-source-range: 14.232.166.121/32, 113.20.108.35/32, 118.70.125.152/32
    hosts:
      - host: speedtest.prod.ftech.ai
        paths:
          - path: /
    tls:
      - secretName: speedtest-tls
        hosts:
          - speedtest.prod.ftech.ai
  service:
    type: ClusterIP
    port: 3000