---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trongpt

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trongpt-admin-view
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trongpt-admin-crb
subjects:
- kind: ServiceAccount
  name: trongpt 
  namespace: "users"
roleRef:
  kind: ClusterRole
  name: trongpt-admin-view
  apiGroup: rbac.authorization.k8s.io
