apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: devsecops
    server: https://kubernetes.default.svc
  project: devsecops
  source:
    repoURL: https://gitlab.ftech.ai/devops/gitops/argocd/manifest/is-chart.git
    targetRevision: master
    path: kyverno/helm
    helm:
     releaseName: kyverno-local
     version: v3
     valueFiles:
     - values-local.yaml
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - FailOnSharedResource=true
    - ServerSideApply=true
