apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Privilege escalation, such as via set-user-ID or set-group-ID file mode, should not be allowed.
      This policy ensures the `allowPrivilegeEscalation` field is set to `false`.      
spec:
  validationFailureAction: enforce
  rules:
    - exclude:
        resources: {}
      generate:
        clone: {}
      match:
        any:
          - resources:
              kinds:
                - Pod
        resources: {}
      mutate: {}
      name: privilege-escalation
      validate:
        message: >-
          Privilege escalation is disallowed. The fields
          spec.containers[*].securityContext.allowPrivilegeEscalation,
          spec.initContainers[*].securityContext.allowPrivilegeEscalation, and
          spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation
          must be set to `false`.          
        pattern:
          spec:
            '=(ephemeralContainers)':
              - securityContext:
                  allowPrivilegeEscalation: 'false'
            '=(initContainers)':
              - securityContext:
                  allowPrivilegeEscalation: 'false'
            containers:
              - securityContext:
                  allowPrivilegeEscalation: 'false'
    - exclude:
        resources: {}
      generate:
        clone: {}
      match:
        any:
          - resources:
              kinds:
                - DaemonSet
                - Deployment
                - Job
                - StatefulSet
        resources: {}
      mutate: {}
      name: autogen-privilege-escalation
      validate:
        message: >-
          Privilege escalation is disallowed. The fields
          spec.containers[*].securityContext.allowPrivilegeEscalation,
          spec.initContainers[*].securityContext.allowPrivilegeEscalation, and
          spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation
          must be set to `false`.          
        pattern:
          spec:
            template:
              spec:
                '=(ephemeralContainers)':
                  - securityContext:
                      allowPrivilegeEscalation: 'false'
                '=(initContainers)':
                  - securityContext:
                      allowPrivilegeEscalation: 'false'
                containers:
                  - securityContext:
                      allowPrivilegeEscalation: 'false'
    - exclude:
        resources: {}
      generate:
        clone: {}
      match:
        any:
          - resources:
              kinds:
                - CronJob
        resources: {}
      mutate: {}
      name: autogen-cronjob-privilege-escalation
      validate:
        message: >-
          Privilege escalation is disallowed. The fields
          spec.containers[*].securityContext.allowPrivilegeEscalation,
          spec.initContainers[*].securityContext.allowPrivilegeEscalation, and
          spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation
          must be set to `false`.          
        pattern:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    '=(ephemeralContainers)':
                      - securityContext:
                          allowPrivilegeEscalation: 'false'
                    '=(initContainers)':
                      - securityContext:
                          allowPrivilegeEscalation: 'false'
                    containers:
                      - securityContext:
                          allowPrivilegeEscalation: 'false'