{{- if .Values.externalSecrets.create -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: external-secrets.io/v1beta1
{{- else -}}
apiVersion: external-secrets.io/v1alpha1
{{- end }}
kind: SecretStore
metadata:
  name: {{ include "app.fullname" . }}
spec:
  provider:
    {{- with .Values.externalSecrets.vault }}
    vault:
      {{- toYaml . | nindent 6 }}
    {{- end }}  
    # vault:
    #   server: "https://vault.tool.ftech.ai"
    #   auth:
    #     kubernetes:
    #       mountPath: "kubernetes"
    #       role: "argocd-templates-nginx-manifest-ro"
{{- end }}    
