{{- if .Values.priorityClass.enabled -}}
---
kind: PriorityClass
apiVersion: scheduling.k8s.io/v1
metadata:
  name: high-priority
value: 10000
globalDefault: false
description: "high priority class"
{{ end }}